Практика 8
DenPuV/pract_math_and_data pull request #1
Opened 2021-05-24 17:19 UTC by DenPuV

2021-05-24 18:33 UTC, CheremiskinGleb reviewed
Viewed

2021-06-03 14:12 UTC, CheremiskinGleb commented on 08_pract_regexp/regexp.py
> +regex(emails, regPattern)
Нужна проверка на корректность введённых данных.

2021-06-03 14:13 UTC, CheremiskinGleb commented on 08_pract_regexp/regexp.py
> +regex(ips, regPattern)
Здесь тоже нужна бы проверка введённых данных.

2021-06-03 14:16 UTC, CheremiskinGleb commented on 08_pract_regexp/regexp.py
> +regex(phones, regPattern)
Здесь тоже проверка была бы не лишней.

2021-06-03 14:16 UTC, CheremiskinGleb reviewed
Review

2021-06-06 06:22 UTC, stanislavlyalin requested changes

2021-06-06 06:22 UTC, stanislavlyalin commented on 08_pract_regexp/regexp.py
> +regPattern = r'([-0-9A-z\.]{1,})@([0-9A-Za-z]{1,}).([0-9A-Za-z]{1,})'
* `{1,}` можно заменить на `+`
* точку нужно экранировать

2021-06-07 03:33 UTC, merged