Практика 6
DenPuV/pract_math_and_data pull request #2
Opened 2021-05-24 17:20 UTC by DenPuV

2021-05-24 18:32 UTC, CheremiskinGleb reviewed
Комментарий для практики 6

2021-06-03 14:05 UTC, CheremiskinGleb commented on 06_pract_regression/regression.py
> +im = Image.open('image.jpg')
Нужна проверка на наличие файла, а также данных в нём.

2021-06-03 14:09 UTC, CheremiskinGleb commented on 06_pract_regression/regression.py
> +X = np.array([x, x**2.0, x**3.0, x**4.0, x**5.0]).transpose()
Надо бы добавить проверку размерности массива.

2021-06-03 14:09 UTC, CheremiskinGleb reviewed
Review

2021-06-06 06:19 UTC, stanislavlyalin requested changes

2021-06-06 06:19 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +plt.show()
Устранить дублирование, используя цикл

2021-06-07 03:34 UTC, merged