Практика 4
DenPuV/pract_math_and_data pull request #3
Opened 2021-05-24 17:20 UTC by DenPuV

2021-05-24 18:32 UTC, CheremiskinGleb reviewed
Viewed

2021-06-03 13:47 UTC, CheremiskinGleb commented on 04_pract_kNN/run.py
> +obj = np.array([height, weight])
Нужна проверка корректности введённых данных.

2021-06-03 13:52 UTC, CheremiskinGleb commented on 04_pract_kNN/kNN.py
> +# классификация методом k ближайших соседей
Лучше подробную инструкцию сокращать до краткого пояснения задачи функции, иначе занимает слишком много места.

2021-06-03 14:00 UTC, CheremiskinGleb reviewed
Review

2021-06-06 06:08 UTC, stanislavlyalin requested changes

2021-06-06 06:08 UTC, stanislavlyalin commented on 04_pract_kNN/kNN.py
> +        sub_X[:, i] = (sub_X[:, i] - av[i])/dev[i]
Можно обойтись без циклов. `numpy` позволяет выполнять операции с векторами поэлементно:
```python
a = np.array([2, 4, 6])
b = np.array([2, 2, 2])
c = np.array([3, 2, 1])
a / b + c  # [4., 4., 4.]
```

2021-06-06 06:08 UTC, stanislavlyalin commented on 04_pract_kNN/kNN.py
> +def k_nearest(X, k, obj):
Преобразуйте функцию в класс:
* в конструкторе задавайте параметр `k` - число соседей
* в метод `fit` передавайте матрицу `X`, выполните её нормализацию, сохраняйте её и параметры нормализации внутри класса
* в методе `predict` выполняйте предсказание для объекта `obj`. Не забудьте выполнить его нормализацию с параметрами, которые сохранили в `fit`

2021-06-07 03:31 UTC, merged