Практика 2
DenPuV/pract_math_and_data pull request #4
Opened 2021-05-24 17:20 UTC by DenPuV

2021-05-24 18:30 UTC, CheremiskinGleb reviewed
Комментарий для практики 2

2021-06-03 13:32 UTC, CheremiskinGleb commented on 02_pract_python/intro_var10.py
> +    answer = input("Введите результат перемножения " + x + " и " + y + " : ")
Надо бы сделать проверку введённых данных, иначе при вводе некорректных данных выдаёт ошибку.

2021-06-03 13:40 UTC, CheremiskinGleb commented on 02_pract_python/intro_var10.py
> +print(genMas(10, 5))
Лучше проверять введённые параметры на корректность ввода, чтобы не возникали ошибки.

2021-06-03 13:40 UTC, CheremiskinGleb commented on 02_pract_python/intro_var10.py
> +print(minAndMax(10))
Здесь тоже надо бы сделать проверку.

2021-06-03 13:43 UTC, CheremiskinGleb reviewed
Viewed2

2021-06-04 02:56 UTC, stanislavlyalin requested changes

2021-06-04 02:56 UTC, stanislavlyalin commented on 02_pract_python/intro_var10.py
> +    if(k <= 0 and k <= 0):
Опечатка: дважды проверяете одно и то же значение

2021-06-04 02:56 UTC, stanislavlyalin commented on 02_pract_python/intro_var10.py
> +        li[i] = [random.randint(0, 100) for i in range(n)]
Можно объединить в одну строку кода:
```python
li = [[<генерация массива размера n>] for i in range(k)]
```

2021-06-04 02:56 UTC, stanislavlyalin commented on 02_pract_python/intro_var10.py
> +    return temp
Можно упростить:
```python
return max(li, key=lambda arr: sum(arr))
```

2021-06-04 02:56 UTC, stanislavlyalin commented on 02_pract_python/intro_var10.py
> +    y = input("Введите второе число: ")
Добавьте проверку через `try-except`, что `x` и `y` целые числа

2021-06-04 13:28 UTC, merged