Практика 3
DenPuV/pract_math_and_data pull request #5
Opened 2021-05-24 18:14 UTC by CheremiskinGleb

2021-05-24 18:28 UTC, DenPuV reviewed
Viewed

2021-05-24 18:28 UTC, DenPuV reviewed
Viewed

2021-06-02 18:11 UTC, DenPuV commented on 03_pract_kmeans/k_means.py
> +  r = np.sqrt(np.sum(np.power(A - B, 2)))
Вместо np.power можно использовать оператор **
тогда выражение станет короче и понятнее

2021-06-02 18:11 UTC, DenPuV commented on 03_pract_kmeans/k_means.py
> +  m = X.shape[0]
Выдает исключение IndexError: tuple index out of range если массив X пустой

2021-06-02 18:11 UTC, DenPuV commented on 03_pract_kmeans/run.py
> +plt.plot(X[:,0], X[:,1], 'bx', ans[:,0], ans[:,1], 'r*', markersize=20)
Тут пригодилась бы проверка размерности массива Х

2021-06-06 05:16 UTC, stanislavlyalin requested changes

2021-06-06 05:16 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +  # Для вычисления квадратного корня используйте функцию np.sqrt
Комментарии TODO здесь и ниже засоряют код. Они нужны были только как подсказки при выполнении практики. Сейчас их можно удалить

2021-06-06 05:16 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +  r = np.sqrt(np.sum((A - B) ** 2))
Проверить, что `A` и `B` являются типами `numpy.ndarray`

2021-06-06 05:16 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +  return r
Можно не вводить переменную `r`, тогда реализация сократится до 1 строки

2021-06-06 05:16 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +  n = X.shape[1]
Можно объединить:
```python
m, n = X.shape
```

2021-06-06 05:16 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +def kmeans(k, X):
Переделайте функцию `kmeans` в класс с таким интерфейсом:
* в конструкторе класса задавайте параметр `k` - количество искомых кластеров
* добавьте метод `fit`, который принимает матрицу `X` и возвращает координаты центров найденных кластеров

2021-06-07 03:29 UTC, merged