Практика 5
DenPuV/pract_math_and_data pull request #6
Opened 2021-05-24 18:14 UTC by CheremiskinGleb

2021-05-24 18:30 UTC, DenPuV reviewed
Работает

2021-06-02 18:33 UTC, DenPuV commented on 05_pract_decision_tree/decision_tree.py
> +
Можно добавить проверку на размерность массива

2021-06-02 18:33 UTC, DenPuV commented on 05_pract_decision_tree/decision_tree.py
> +def decision_tree(X, Y, scale, level=0):
При некорректных входных данных (в массивах X и Y) функция может не выйти из рекурсии.
Можно поставить ограничение на количество уровней

2021-06-02 18:34 UTC, DenPuV commented on 05_pract_decision_tree/decision_tree.py
> +    m = X.shape[0]  # количество примеров
Можно добавить проверку на размерность массива

2021-06-06 06:15 UTC, stanislavlyalin requested changes

2021-06-06 06:15 UTC, stanislavlyalin commented on 05_pract_decision_tree/classify.py
> +    # TODO: пользуясь информацией, выведенной на экран в процессе построения
Комментарии `TODO` удалить по всему коду

2021-06-06 06:15 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +    m = X.shape[0]  # количество примеров
m, n = X.shape

2021-06-06 06:15 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +                gain.append(info - info_s)
Можно упростить, используя функцию `zip`:
```python
for x_value, value_count in zip(values, counts):
    info_s += (value_count/m) * Info(Y[X[:, i] == x_value])
    gain.append(info - info_s)
```

2021-06-06 06:15 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +    for i in range(len(np.unique(set))):
Здесь можно упростить, итерируясь только по значениям `counts`:
```python
for count in counts:
    p_i = count/len(set)
    info += p_i*np.log2(p_i) if p_i > 0 else 0
```

2021-06-07 03:32 UTC, merged